apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\hp\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert --out k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: file-storage-2
  name: file-storage-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: file-storage-2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\hp\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert --out k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: file-storage-2
    spec:
      containers:
        - args:
            - sh
            - -c
            - "mvn clean compile && \n       mvn exec:java -Dexec.mainClass=com.example.filestorage.FileStorageApp"
          env:
            - name: CONTAINER_ID
              value: storage-2
            - name: CONTAINER_INDEX
              value: "2"
            - name: MAVEN_OPTS
              value: -Xmx256m
            - name: MQTT_BROKER_URL
              value: tcp://filemanager-mqtt:1883
            - name: SFTP_PORT
              value: "2202"
            - name: STORAGE_PORT
              value: "8083"
            - name: VOLUME_GROUP
              value: "2"
          image: maven:3.9.6-eclipse-temurin-22
          name: filemanager-storage-2
          volumeMounts:
            - mountPath: /app
              name: file-storage-2-cm0
            - mountPath: /storage/data
              name: storage-volume-2
            - mountPath: /root/.m2
              name: maven-repo
          workingDir: /app
      restartPolicy: Always
      volumes:
        - configMap:
            name: file-storage-2-cm0
          name: file-storage-2-cm0
        - name: storage-volume-2
          persistentVolumeClaim:
            claimName: storage-volume-2
        - name: maven-repo
          persistentVolumeClaim:
            claimName: maven-repo
