apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\hp\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert --out k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: main-app
  name: main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: main-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\hp\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert --out k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: main-app
    spec:
      containers:
        - env:
            - name: MQTT_BROKER_URL
              value: tcp://filemanager-mqtt:1883
            - name: MYSQL_DATABASE
              value: filemanager
            - name: MYSQL_HOST
              value: filemanager-mysql
            - name: MYSQL_PASSWORD
              value: fileapp123
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: fileapp
            - name: SQLITE_DB_PATH
              value: /app/data/fileapp.db
          image: pedrombmachado/ntu_lubuntu:soft40051
          name: filemanager-mainapp
          ports:
            - containerPort: 3389
              protocol: TCP
            - containerPort: 22
              protocol: TCP
      restartPolicy: Always
