apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\hp\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert --out k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: main-app
  name: main-app
spec:
  ports:
    - name: "3390"
      port: 3390
      targetPort: 3389
    - name: "2022"
      port: 2022
      targetPort: 22
  selector:
    io.kompose.service: main-app
