apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\hp\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert --out k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: mqtt-broker
  name: mqtt-broker
spec:
  ports:
    - name: "1883"
      port: 1883
      targetPort: 1883
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    io.kompose.service: mqtt-broker
